id: P33932363
initial_creation_type: input
source_metadata:
  Title: Two Buddhist texts in Sanskrit
  Editor: Banerjee, A.C.
  Publisher: The World Press Private Ltd
  Place of Publication: Calcutta
  Year: '1977'
  Bhikṣukarmavākya:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:15:27.755414'
last_modified_at: '2022-03-08T16:15:27.755422'
